/* Generated By:JavaCC: Do not edit this line. MyParserTreeConstants.java Version 5.0 */
package parser;

public interface MyParserTreeConstants
{
  public int JJTDOPARSE = 0;


  public String[] jjtNodeName = {
    "doParse",
  };
}
/* JavaCC - OriginalChecksum=2835b8a75ddc6b03d8fb78415a78ecbf (do not edit this line) */
